---
- name: Creating backup to /etc
  hosts: backup
  remote_user: vagrant
  become: true
  
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present

    - name: Install borgbackup
      yum:
        name: borgbackup
        state: latest
        
    - name: Creating user 'borg'

