Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
    end

    config.vm.define "backup" do |backup|

        backup.vm.hostname = "backup"

        backup.vm.provider "virtualbox" do |vb|
            vb.customize ["createhd",  "--filename", "backup_disk", "--size", "1024"]
            vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
            vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "1", "--type", "hdd", "--medium", "backup_disk.vdi"]
        end

	backup.vm.provision "shell", inline: <<-SHELL
#!/bin/bash
sudo fdisk /dev/sdb <<EOF
n
p
1


w
EOF
sudo mkfs.ext4 /dev/sdb1
sudo mkdir /var/backup
sudo mount /dev/sdb1 /var/backup
	SHELL

        backup.vm.network "private_network", ip: "192.168.10.10"
    end

    config.vm.define "client" do |client|

        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "192.168.10.20"
    end
end
